# Generated by Django 4.0 on 2023-05-13 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_time',
            field=models.TimeField(default=datetime.time(21, 26, 21, 898840)),
        ),
        migrations.AddField(
            model_name='task',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
