# Generated by Django 4.0 on 2023-05-13 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_expected_date_task_expected_time_task_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expected_time',
            field=models.TimeField(default=datetime.time(22, 14, 8, 354139)),
        ),
    ]
