# Generated by Django 4.0 on 2023-05-14 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_message_systemlog_log_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 19, 43, 57, 171516, tzinfo=utc)),
        ),
    ]
