# Generated by Django 4.0 on 2023-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_expected_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expected_time',
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
