# Generated by Django 4.0 on 2023-05-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_task_expected_time_task_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='expected_date',
            new_name='due_date',
        ),
    ]
