# Generated by Django 4.0 on 2023-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_time',
            field=models.IntegerField(default=1),
        ),
    ]
